# ServiceMonitor for Sealed Secrets Controller Metrics (scrapes via sealed-secrets-controller-metrics Service, port metrics:8081)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sealed-secrets-controller-metrics
  namespace: kube-system
  labels:
    app: k8s
spec:
  selector:
    matchLabels:
      name: sealed-secrets-controller
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
